import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'


const Home: NextPage = () => {
  return (
    <div className='m-0 min'>
      <Head>
        <title>Travel Plus App</title>
        <meta name="travel plus" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='w-100% h-96 relative'>
        <Image
          src='/images/hero.jpg'
          alt='cover picture'
          layout='fill'
          objectFit='cover'
          priority={true}
          />
        </div>
        <p>hello world</p>
    </div>
  )
}

export default Home
