import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className='m-0 min'>
      <Head>
        <title>Travel Plus App</title>
        <meta name="travel plus" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <header className='fixed'>
          <h1 className="text-3xl text-bold text-left text-purple-700 p-4" >Travel Plus</h1>
        </header>
        <main>
          <Home/>
        </main>
        <footer className={styles.footer}>
          
        </footer>
    </div>
  )
}

export default Home
